"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.condition_return import ConditionReturn
from neurostore_sdk.model.metadata import Metadata
globals()['ConditionReturn'] = ConditionReturn
globals()['Metadata'] = Metadata
from neurostore_sdk.model.condition_list import ConditionList


class TestConditionList(unittest.TestCase):
    """ConditionList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConditionList(self):
        """Test ConditionList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConditionList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
