"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.json_ld_context import JsonLdContext


class TestJsonLdContext(unittest.TestCase):
    """JsonLdContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJsonLdContext(self):
        """Test JsonLdContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JsonLdContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
