"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.annotation_return import AnnotationReturn
from neurostore_sdk.model.metadata import Metadata
globals()['AnnotationReturn'] = AnnotationReturn
globals()['Metadata'] = Metadata
from neurostore_sdk.model.annotation_list import AnnotationList


class TestAnnotationList(unittest.TestCase):
    """AnnotationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationList(self):
        """Test AnnotationList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
