"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.read_only import ReadOnly
from neurostore_sdk.model.study import Study
from neurostore_sdk.model.studyset import Studyset
globals()['ReadOnly'] = ReadOnly
globals()['Study'] = Study
globals()['Studyset'] = Studyset
from neurostore_sdk.model.studyset_return import StudysetReturn


class TestStudysetReturn(unittest.TestCase):
    """StudysetReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudysetReturn(self):
        """Test StudysetReturn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudysetReturn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
