"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.analysis import Analysis
from neurostore_sdk.model.read_only import ReadOnly
globals()['Analysis'] = Analysis
globals()['ReadOnly'] = ReadOnly
from neurostore_sdk.model.study import Study


class TestStudy(unittest.TestCase):
    """Study unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudy(self):
        """Test Study"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Study()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
