"""
    neurostore api

    Create datasets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_api
from neurostore_api.model.image import Image
from neurostore_api.model.read_only import ReadOnly
globals()['Image'] = Image
globals()['ReadOnly'] = ReadOnly
from neurostore_api.model.image_return import ImageReturn


class TestImageReturn(unittest.TestCase):
    """ImageReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageReturn(self):
        """Test ImageReturn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ImageReturn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
