"""
    neurostore api

    Create datasets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_api
from neurostore_api.model.annotation_note import AnnotationNote
from neurostore_api.model.read_only import ReadOnly
globals()['AnnotationNote'] = AnnotationNote
globals()['ReadOnly'] = ReadOnly
from neurostore_api.model.annotation import Annotation


class TestAnnotation(unittest.TestCase):
    """Annotation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotation(self):
        """Test Annotation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Annotation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
