"""
    neurostore api

    Create datasets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_api
from neurostore_api.model.metadata import Metadata
globals()['Metadata'] = Metadata
from neurostore_api.model.inline_response2007 import InlineResponse2007


class TestInlineResponse2007(unittest.TestCase):
    """InlineResponse2007 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2007(self):
        """Test InlineResponse2007"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2007()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
