"""
    neurostore api

    Create datasets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_api
from neurostore_api.model.metadata import Metadata
from neurostore_api.model.user import User
globals()['Metadata'] = Metadata
globals()['User'] = User
from neurostore_api.model.user_list import UserList


class TestUserList(unittest.TestCase):
    """UserList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserList(self):
        """Test UserList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
