"""
    neurostore api

    Create datasets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_api
from neurostore_api.model.point import Point
from neurostore_api.model.point_value import PointValue
from neurostore_api.model.read_only import ReadOnly
globals()['Point'] = Point
globals()['PointValue'] = PointValue
globals()['ReadOnly'] = ReadOnly
from neurostore_api.model.point_return import PointReturn


class TestPointReturn(unittest.TestCase):
    """PointReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPointReturn(self):
        """Test PointReturn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PointReturn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
