"""
    neurostore api

    Create datasets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_api
from neurostore_api.model.annotation_return import AnnotationReturn


class TestAnnotationReturn(unittest.TestCase):
    """AnnotationReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationReturn(self):
        """Test AnnotationReturn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationReturn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
