"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.metadata import Metadata
from neurostore_sdk.model.point_return import PointReturn
globals()['Metadata'] = Metadata
globals()['PointReturn'] = PointReturn
from neurostore_sdk.model.point_list import PointList


class TestPointList(unittest.TestCase):
    """PointList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPointList(self):
        """Test PointList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PointList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
