"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.inline_response422 import InlineResponse422


class TestInlineResponse422(unittest.TestCase):
    """InlineResponse422 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse422(self):
        """Test InlineResponse422"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse422()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
