"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.condition import Condition
from neurostore_sdk.model.read_only import ReadOnly
globals()['Condition'] = Condition
globals()['ReadOnly'] = ReadOnly
from neurostore_sdk.model.condition_return import ConditionReturn


class TestConditionReturn(unittest.TestCase):
    """ConditionReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConditionReturn(self):
        """Test ConditionReturn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConditionReturn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
