"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import neurostore_sdk
from neurostore_sdk.api.studies_api import StudiesApi  # noqa: E501


class TestStudiesApi(unittest.TestCase):
    """StudiesApi unit test stubs"""

    def setUp(self):
        self.api = StudiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_studies_get(self):
        """Test case for studies_get

        GET a list of studies  # noqa: E501
        """
        pass

    def test_studies_id_delete(self):
        """Test case for studies_id_delete

        DELETE a study  # noqa: E501
        """
        pass

    def test_studies_id_get(self):
        """Test case for studies_id_get

        GET a study  # noqa: E501
        """
        pass

    def test_studies_id_put(self):
        """Test case for studies_id_put

        PUT/update a study  # noqa: E501
        """
        pass

    def test_studies_post(self):
        """Test case for studies_post

        POST/create a study  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
