"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import neurostore_sdk
from neurostore_sdk.api.user_api import UserApi  # noqa: E501


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_get(self):
        """Test case for users_get

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_users_id_get(self):
        """Test case for users_id_get

        Individual User Profile  # noqa: E501
        """
        pass

    def test_users_id_put(self):
        """Test case for users_id_put

        Update Individual Profile  # noqa: E501
        """
        pass

    def test_users_post(self):
        """Test case for users_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
