"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.json_ld_context import JsonLdContext
globals()['JsonLdContext'] = JsonLdContext
from neurostore_sdk.model.json_ld import JsonLd


class TestJsonLd(unittest.TestCase):
    """JsonLd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJsonLd(self):
        """Test JsonLd"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JsonLd()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
