"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurostore_sdk
from neurostore_sdk.model.read_only import ReadOnly
from neurostore_sdk.model.study import Study
globals()['ReadOnly'] = ReadOnly
globals()['Study'] = Study
from neurostore_sdk.model.studyset import Studyset


class TestStudyset(unittest.TestCase):
    """Studyset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudyset(self):
        """Test Studyset"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Studyset()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
