"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import neurostore_sdk
from neurostore_sdk.api.analyses_api import AnalysesApi  # noqa: E501


class TestAnalysesApi(unittest.TestCase):
    """AnalysesApi unit test stubs"""

    def setUp(self):
        self.api = AnalysesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_analyses_get(self):
        """Test case for analyses_get

        GET list of analyses  # noqa: E501
        """
        pass

    def test_analyses_id_delete(self):
        """Test case for analyses_id_delete

        DELETE an analysis  # noqa: E501
        """
        pass

    def test_analyses_id_get(self):
        """Test case for analyses_id_get

        GET an analysis  # noqa: E501
        """
        pass

    def test_analyses_id_put(self):
        """Test case for analyses_id_put

        PUT/update an analysis  # noqa: E501
        """
        pass

    def test_analyses_post(self):
        """Test case for analyses_post

        POST/create an analysis  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
