"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import neurostore_sdk
from neurostore_sdk.api.annotations_api import AnnotationsApi  # noqa: E501


class TestAnnotationsApi(unittest.TestCase):
    """AnnotationsApi unit test stubs"""

    def setUp(self):
        self.api = AnnotationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_annotations_get(self):
        """Test case for annotations_get

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_annotations_id_delete(self):
        """Test case for annotations_id_delete

        DELETE an annotation  # noqa: E501
        """
        pass

    def test_annotations_id_get(self):
        """Test case for annotations_id_get

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_annotations_id_put(self):
        """Test case for annotations_id_put

        Update an annotation  # noqa: E501
        """
        pass

    def test_annotations_post(self):
        """Test case for annotations_post

        Post Annotation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
