"""
    neurostore api

    Create studysets for meta-analysis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import neurostore_sdk
from neurostore_sdk.api.points_api import PointsApi  # noqa: E501


class TestPointsApi(unittest.TestCase):
    """PointsApi unit test stubs"""

    def setUp(self):
        self.api = PointsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_points_get(self):
        """Test case for points_get

        Get Points  # noqa: E501
        """
        pass

    def test_points_id_delete(self):
        """Test case for points_id_delete

        DELETE a point  # noqa: E501
        """
        pass

    def test_points_id_get(self):
        """Test case for points_id_get

        GET a point  # noqa: E501
        """
        pass

    def test_points_id_put(self):
        """Test case for points_id_put

        PUT/update a point  # noqa: E501
        """
        pass

    def test_points_post(self):
        """Test case for points_post

        POST Points  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
